apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  annotations:
    container.apparmor.security.beta.kubernetes.io/secure-nginx: localhost/docker-nginx
  labels:
    run: secure-nginx
  name: secure-nginx
spec:
  containers:
  - image: nginx:1.27
    name: secure-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
