apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container
  name: multi-container
  namespace: q13
spec:
  containers:
  - image: nginx:1.22.1
    name: nginx
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
            fieldPath: spec.nodeName
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: busybox:1.31.1
    name: busybox-writer
    command: [ "sh", "-c" ]
    args: ["while true; do date >> /cache/date.log; sleep 1; done"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: busybox:1.31.1
    name: busybox-reader
    command: [ "sh", "-c" ]
    args: ["tail -f /cache/date.log"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi