apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-schedule
  name: nginx-schedule
  namespace: question9
spec:
  nodeName: k8s
  containers:
  - image: nginx:1.22.1
    name: nginx-schedule
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
