---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: question6
spec: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data-pvc
  namespace: question6
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
