---
apiVersion: v1
data:
  halt: MTIzNA==
kind: Secret
metadata:
  creationTimestamp: null
  name: nginx-secret
  namespace: q19
---
apiVersion: v1
data:
  pass: MTIzNA==
  user: dXNlcjE=
kind: Secret
metadata:
  creationTimestamp: null
  name: nginx-secret2
  namespace: q19
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-secret
  name: nginx-secret
  namespace: q19
spec:
  containers:
  - image: nginx:1.22.1
    name: nginx
    env:
    - name: APP_USER
      valueFrom:
        secretKeyRef:
          name: nginx-secret2
          key: user
    - name: APP_PASS
      valueFrom:
        secretKeyRef:
          name: nginx-secret2
          key: pass
    volumeMounts:
    - name: secret
      mountPath: "/tmp/secret1"
      readOnly: true
  volumes:
  - name: secret
    secret:
      secretName: nginx-secret

