apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-single-env
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: KEY1
          valueFrom:
            secretKeyRef:
              name: nginx-secret-file
              key: KEY1
