apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret-volume-mount
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-secret-volume
      mountPath: "/secret"
      readOnly: true
  volumes:
  - name: nginx-secret-volume
    secret:
      secretName: nginx-secret-file
