apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-volume-mount
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-configmap-volume
      mountPath: "/config"
      readOnly: true
  volumes:
  - name: nginx-configmap-volume
    configMap:
      name: nginx-configmap-file
