apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-single-env
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: KEY1
          valueFrom:
            configMapKeyRef:
              name: nginx-configmap-file
              key: KEY1
