apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret-stringdata
data:
  KEY1: MTIzNA==
  KEY2: MTIzNA==
  KEY3: MTIzNCA1Njc4
stringData:
  KEY1_UNENCODED: "1234"
  KEY2_UNENCODED: "1234"
  KEY3_UNENCODED: "1234 5678"
