apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
spec:
  volumes:
    - name: username-volume
      secret:
        secretName: username
    - name: password-volume
      secret:
        secretName: password
  containers:
  - image: nginx
    name: secret-pod-with-volume
    resources: {}
    volumeMounts:
      - name: username-volume
        readOnly: true
        mountPath: "/etc/username-volume"
      - name: password-volume
        readOnly: true
        mountPath: "/etc/password-volume"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}