apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod-with-env
  name: secret-pod-with-env
spec:
  containers:
  - image: nginx
    name: secret-pod-with-volume
    resources: {}
    env:
     - name: USERNAME
       valueFrom:
         secretKeyRef:
           name: username
           key: user
     - name: PASSWORD
       valueFrom:
         secretKeyRef:
           name: password
           key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}